name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build /Junggyu/. --file /Junggyu/Dockerfile --tag mypython:latest
      # Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mypython%3Alatest&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
      # chmod 666 /var/run/docker.sock

    - name: Harbor login
      run: docker login 52.79.185.138 -u admin -p Cloudclub123

    - name: Image tagging
      run: docker tag mypython:latest 52.79.185.138/junggyu/junggy:latest

    - name: Push image to Harbor
      run: docker push 52.79.185.138/junggyu/junggy:latest